name: aws-deploy
run-name: Deploy to AWS PROD
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: 'eu-central-1'

jobs:
  deploy-prod:
    name: Deploy AWS PROD
    environment: prod
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: 'eu-central-1'

      - name: Bootstrap
        run: npm run cdk bootstrap
        env:
          CDK_ENV_NAME: prod
          ALLOWED_UPLOAD_ORIGINS: ${{ env.ALLOWED_UPLOAD_ORIGINS }}

      - name: Diff stack
        run: npm run cdk diff
        env:
          CDK_ENV_NAME: prod
          ALLOWED_UPLOAD_ORIGINS: ${{ env.ALLOWED_UPLOAD_ORIGINS }}

      - name: Deploy stack
        run: npx cdk deploy --all --require-approval never
        env:
          CDK_ENV_NAME: prod
          ALLOWED_UPLOAD_ORIGINS: ${{ env.ALLOWED_UPLOAD_ORIGINS }}
